[tool.isort]
force_grid_wrap = 0
force_single_line = true
include_trailing_comma = true
line_length = 79
lines_after_imports = 2
multi_line_output = 3
use_parentheses = true

[tool.black]
line-length = 79
target-version = ['py37']
include = '\.pyi?$'
safe = true
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
